from collections.abc import Sequence
from typing import Literal

from jax import Array

from . import linalg

def mean(arr: Array, axis: int = -1) -> Array: ...
def sum(arr: Array, axis: int = -1) -> Array: ...  # noqa: A001
def sqrt(arr: Array) -> Array: ...
def where(cond: Array, left: Array | float, right: Array | float) -> Array: ...
def all(arr: Array) -> Array: ...  # noqa: A001
def isfinite(arr: Array) -> Array: ...
def concatenate(arrays: Sequence[Array], axis: int = 0) -> Array: ...
def stack(arrays: Sequence[Array], axis: int = 0) -> Array: ...
def corrcoef(left: Array, right: Array) -> Array: ...
def fill_diagonal(
    arr: Array, val: Array | float, *, inplace: Literal[False]
) -> Array: ...
def exp(arr: Array) -> Array: ...
def abs(arr: Array) -> Array: ...  # noqa: A001
def triu_indices(n: int, k: int = 0) -> tuple[Array, Array]: ...
def log(arr: Array) -> Array: ...
def array(obj: object) -> Array: ...
def arccosh(obj: object) -> Array: ...
def allclose(
    left: Array, right: Array, rtol: float = ..., atol: float = ...
) -> Array: ...

inf: float

__all__ = ("linalg",)
